## numpy와 닮은 파이토치 (pytorch)

In [ ]:
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=torch.tensor([1,2, 3.1   , 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

In [ ]:
A = torch.tensor([ [1,2,3], [3,4,5] ]) # 이 셀부터는 import torch 는 실행 했다 치고 작성
# A = torch.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim)  # 차원의 수
print(A.numel()) # 전체 성분의 수

In [ ]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함 10개로

In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [ ]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## pytorch 의 인덱싱 슬라이스

In [ ]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([ [1,2,3], [4,5,6], [7,8,9] ])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [ ]:
# 3차원 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(A[0,1,2])

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[ [True,True,False,False] ])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [ ]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [ ]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## pytorch의 여러 함수들

In [ ]:
A=torch.randn(3,3) # Normal 의 n
B=torch.rand(3,3) # 이건 uniform
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[-2.2280, -0.2655,  0.5285],
        [-1.5944,  0.0820, -0.5476],
        [ 0.5724,  0.3434, -0.5678]])
tensor([[0.5707, 0.2209, 0.7139],
        [0.3488, 0.2078, 0.7612],
        [0.6228, 0.7249, 0.1137]])
tensor([[-2.2280, -0.2655,  0.5285],
        [-1.5944,  0.0820, -0.5476]])


In [ ]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 0.0410, -1.1713, -0.1850],
        [-0.3433, -0.9131, -0.4786],
        [ 0.5371,  0.3436, -1.4821]])
tensor([[0.0410, 1.1713, 0.1850],
        [0.3433, 0.9131, 0.4786],
        [0.5371, 0.3436, 1.4821]])
tensor([[0.2026, 1.0823, 0.4301],
        [0.5859, 0.9556, 0.6918],
        [0.7329, 0.5862, 1.2174]])
tensor([[1.0419, 0.3100, 0.8311],
        [0.7094, 0.4013, 0.6197],
        [1.7111, 1.4100, 0.2272]])
tensor([[-3.1932,  0.1581, -1.6876],
        [-1.0691, -0.0909, -0.7369],
        [-0.6216, -1.0683,  0.3935]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[ 0., -1., -0.],
        [-0., -1., -0.],
        [ 1.,  0., -1.]])
tensor([[ 0.0400, -1.1700, -0.1800],
        [-0.3400, -0.9100, -0.4800],
        [ 0.5400,  0.3400, -1.4800]])
tensor([[ 0., -2., -1.],
        [-1., -1., -1.],
        [ 0.,  0., -2.]])
tensor([[ 1., -1., -0.],
        [-0., -0., -0.],
        [ 1.,  1., -1.]])


In [ ]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [ ]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
A=torch.randn(3,4)
print(A)
# print(torch.max(A))
# print(torch.max(A,dim=0))
print(torch.max(A,dim=1))
# print(torch.max(A,dim=0, keepdims=True))
print(torch.max(A,dim=1, keepdims=True)) # 3 행 1열 짜리 2D tensor
# print(torch.min(A))
# print(torch.min(A,dim=0))
# print(torch.min(A,dim=1))
# print(torch.argmax(A))
# print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
# print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[ 0.8113, -0.2081,  0.7743, -0.3669],
        [ 1.8930,  0.8717,  0.3202, -1.0095],
        [ 0.1797, -1.4584, -0.3759, -0.0517]])
torch.return_types.max(
values=tensor([0.8113, 1.8930, 0.1797]),
indices=tensor([0, 0, 0]))
torch.return_types.max(
values=tensor([[0.8113],
        [1.8930],
        [0.1797]]),
indices=tensor([[0],
        [0],
        [0]]))


In [ ]:
a=torch.randn(6,1)
# print(a)
# a_sorted=torch.sort(a,dim=0)
# print(a_sorted)

# a=torch.randn(6,1)
# print(a)
# print(a.sort(dim=0))
# print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor(1.2925)
tensor(1.2925)
tensor([[0.8971],
        [0.5824],
        [1.2925],
        [0.6241],
        [0.6256],
        [1.8069]])
tensor([[0.8971],
        [0.5824],
        [1.2925],
        [0.6241],
        [0.6256],
        [1.8069]])


In [ ]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[-0.9716, -1.5907, -1.4502, -0.3699],
        [-0.5651,  0.0200,  0.2660, -0.0543],
        [-0.4527, -0.1583,  0.6699,  2.6063]])
tensor(-2.0507)
tensor([-4.3824, -0.3335,  2.6652])
tensor([[-4.3824],
        [-0.3335],
        [ 2.6652]])
tensor(-0.1709)
tensor([-1.0956, -0.0834,  0.6663])
tensor([[-1.0956],
        [-0.0834],
        [ 0.6663]])
tensor(1.0966)
tensor([[-4.3824],
        [-0.3335],
        [ 2.6652]])
tensor([[-1.0956],
        [-0.0834],
        [ 0.6663]])
tensor(1.0966)


In [ ]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

tensor([2, 3, 2, 1, 3, 2, 2, 1, 1, 2, 3, 2])
torch.Size([12])
tensor([[[2, 3, 2],
         [1, 3, 2]],

        [[2, 1, 1],
         [2, 3, 2]]])
3


In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [ ]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [ ]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [ ]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B])
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다.

E=torch.cat([A,B], dim=0)
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)

print(C)
print(D)
print(E)
print(F)
print(G)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([

In [ ]:
A = torch.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [ ]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [ ]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @ 에 대해 좀만 더

In [ ]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [ ]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1)
D=A@B

print(C.shape)
print(D.shape)
print((C-D).abs().max())

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(9.5367e-07)


In [ ]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A)
print(A_repeat)
print(A_repeat.shape)

tensor([[0.8109, 0.0390, 0.5317],
        [0.2592, 0.0011, 0.0123]])
tensor([[[[0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123],
          [0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123],
          [0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123]]],


        [[[0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123],
          [0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123],
          [0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123]]],


        [[[0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.0011, 0.0123, 0.2592, 0.0011, 0.0123],
          [0.8109, 0.0390, 0.5317, 0.8109, 0.0390, 0.5317],
          [0.2592, 0.00

## numpy <-> torch 왔다갔다 가능

In [ ]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])
A=torch.tensor(a) # A=torch.from_numpy(a)
B=b.numpy() # B=np.array(b)
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


## 딥러닝을 가능케한 autograd

In [ ]:
x=torch.tensor([1.], requires_grad=True) # float 이여야해서 1.
print(x)

tensor([1.], requires_grad=True)


In [ ]:
x=torch.tensor([1.])
print(x)
print(x.requires_grad)

x.requires_grad=True
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [ ]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y) # PowBackward0 가 붙어있다!

print(x.grad)
y.backward()
print(x.grad) # y=x**2을 미분한 2x의 x 값에 1을 대입한 gradient 값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y)
# y.retain_grad() # 이걸 하면 y.grad도 볼 수 있다

z=3*y
print(z) # MulBackward0 가 붙어있다!

z.backward()
print(x.grad) # chain rule로 알아냄
# print(y.grad) # warning! 중간건 안된다

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
z=3*y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감 (backward!)
print(x.grad)

tensor([2.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0 가 붙어있다!
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= y*x**2
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([1.])


In [ ]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [ ]:
x=torch.tensor([1.] ,requires_grad=True)
x.requires_grad=False
# tranfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


In [ ]:
x=torch.tensor([2.] ,requires_grad=True)
x=x.detach() # detach도 많이 쓰이는 듯
print(x)
y=x**2
print(y)

tensor([2.])
tensor([4.])


In [ ]:
# detach 와 torch.no_grad
x=torch.tensor([1.], requires_grad=True)
# chain rule을 위해 계속 grad_fu을 update 하니까 grad_fn 잠시 안 계산하고 싶을 때 torch.no_grad
# 모델 테스트 시에는 불필요하게 메모리 쓸 필요 없기 때문!
with torch.no_grad():
    y=x**2
    print(x.requires_grad)
    print(y)
print(x.requires_grad)
# y.backward() # error!
y=x**2
print(y)

x=torch.tensor([1.], requires_grad=True)
x=x.detach()
y = x**2
print(x.requires_grad)
print(y)
# y.backward() # error!

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)
False
tensor([1.])


In [ ]:
# !pip install torchviz
# from torchviz import make_dot
x=torch.tensor([1., 2.],requires_grad=True)
# make_dot(x)
# make_dot(x**2)
# make_dot(x**2+1)
make_dot((x**2+1)**2)

NameError: ignored

## 간단한 인공신경망 만들기

In [ ]:
import torch
from torch import nn

x=torch.tensor([1.])
model = nn.Linear(1,1) # 입력 node 한 개, 출력 node 한 개인 layer 만듦

print(model.weight) # 만들면서 initialize 함
print(model.bias)

y = model(x)
print(y)

y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[-0.7019]], requires_grad=True)
Parameter containing:
tensor([-0.3776], requires_grad=True)
tensor([-1.0795], grad_fn=<AddBackward0>)
tensor([-1.0795], grad_fn=<AddBackward0>)


In [ ]:
fc1 = nn.Linear(1,3) # fully-connected
fc2 = nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

x=torch.tensor([1.])
y = (x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
# nn.Linear 는 개x채x행x열에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다.
# 즉, 노드 하나가 곧 한 채널의 의미한다.
# 따라서, 데이터 여러개를 통과시키고 싶다면 개x채 의 형태로 줘야 함
# why T? weight도 개x채 형태로 만들기 위함!
# 일단, weight shape 개x채에서 채는 무조건 앞에 거 채널 개수와 맞추셈!
# 예를 들어, nn.Linear(2,3) 이면 앞에거 채널 개수는 2 따라서 ?x2 인데
# 두 채널 값을 가지고 3개의 노드를 만드는 거라서 3x2 가 된다!

print(y)
# input size: 1
# fc1.weight.T size: 1x3
# fc1.bias size: 3
# fc2.weight.T size: 3x1
# fc2.bias size: 1

Parameter containing:
tensor([[0.7723],
        [0.8549],
        [0.9242]], requires_grad=True)
Parameter containing:
tensor([ 0.7878, -0.9535, -0.4586], requires_grad=True)
Parameter containing:
tensor([[-0.3404, -0.2877,  0.3690]], requires_grad=True)
Parameter containing:
tensor([-0.1028], requires_grad=True)
tensor([ 1.5601, -0.0986,  0.4656], grad_fn=<AddBackward0>)
tensor([-0.4337], grad_fn=<AddBackward0>)
tensor([-0.4337], grad_fn=<AddBackward0>)


In [ ]:
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

model = nn.Sequential(fc1, fc2) # layer 풀칠
x=torch.tensor([1.])
print(model(x))

tensor([ 0.1443,  1.7302, -0.6704], grad_fn=<AddBackward0>)
tensor([-0.8868], grad_fn=<AddBackward0>)
tensor([-0.8868], grad_fn=<AddBackward0>)


In [ ]:
model = nn.Sequential(nn.Linear(2,5), # 여기는 채,채
                      nn.Linear(5,10),
                      nn.Linear(10,3))

x=torch.randn(2)
print(x)
print(model(x))

x=torch.randn(1,2)
print(x)
print(model(x))

x=torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개를 통과시킴
print(x)
print(model(x))

x=torch.randn(2,3,1,4,5,2)
print(model(x).shape)

tensor([-0.2115, -1.6457])
tensor([0.5339, 0.5663, 0.4219], grad_fn=<AddBackward0>)
tensor([[1.1064, 0.4146]])
tensor([[-0.1059, -0.0736,  0.6442]], grad_fn=<AddmmBackward0>)
tensor([[ 0.7434, -0.2427],
        [-0.4870, -0.8473],
        [ 0.4725,  0.1137],
        [-1.1611, -0.3709],
        [-0.5012, -1.5173]])
tensor([[0.0809, 0.1192, 0.5892],
        [0.5228, 0.4744, 0.2909],
        [0.1205, 0.1075, 0.4898],
        [0.6698, 0.5209, 0.0719],
        [0.6060, 0.6002, 0.3330]], grad_fn=<AddmmBackward0>)
torch.Size([2, 3, 1, 4, 5, 3])


In [ ]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(2,5)
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        x = self.fc2(x)
        x = self.sig2(x)
        x = self.fc3(x)
        x = self.sig3(x)
        return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[0.5575, 0.4830, 0.3394],
        [0.5563, 0.4828, 0.3374],
        [0.5553, 0.4824, 0.3361],
        [0.5579, 0.4833, 0.3401],
        [0.5554, 0.4824, 0.3362]], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model)
print(model.fc1.weight)
print(model.fc2.bias)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)
Parameter containing:
tensor([[-0.1498, -0.1774],
        [-0.1540,  0.5480],
        [ 0.3895,  0.4730],
        [-0.0553,  0.5704],
        [-0.4322, -0.5768]], requires_grad=True)
Parameter containing:
tensor([ 0.2966,  0.1743, -0.3898, -0.2966, -0.0614, -0.4197,  0.0460,  0.2574,
         0.0189, -0.4241], requires_grad=True)


In [ ]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Sequential(
            nn.Linear(2,5),
            nn.Sigmoid(),
            nn.Linear(5,10),
            nn.Sigmoid(),
            nn.Linear(10,3),
            nn.Sigmoid())

    def forward(self,x):
        x = self.linear(x)
        return x

model2 = MyModel2()
x = torch.randn(5,2)
y = model2(x)
print(y)

tensor([[-0.2647, -0.1091],
        [-0.6967, -0.0215],
        [-0.4770, -0.1498],
        [-0.2531,  1.0208],
        [ 0.1609, -0.3029]])


In [ ]:
print(model2)
print(model2.linear[0].weight)
print(model2.linear[-2].bias)

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[ 0.5882, -0.1803],
        [-0.3234,  0.6736],
        [ 0.1816, -0.3730],
        [-0.5313,  0.1610],
        [-0.2035, -0.4490]], requires_grad=True)
Parameter containing:
tensor([-0.2463, -0.3069, -0.2348], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1498, -0.1774],
         [-0.1540,  0.5480],
         [ 0.3895,  0.4730],
         [-0.0553,  0.5704],
         [-0.4322, -0.5768]], requires_grad=True), Parameter containing:
 tensor([ 0.5022, -0.5783,  0.3279, -0.1828, -0.2740], requires_grad=True), Parameter containing:
 tensor([[-1.9592e-04, -3.1074e-01,  9.8688e-02,  1.2608e-02, -4.2887e-01],
         [-3.2016e-02, -3.8420e-01,  1.4005e-01, -3.2193e-02,  1.2688e-01],
         [ 1.2562e-01,  8.4013e-02, -1.1773e-01, -8.5302e-02, -4.4347e-01],
         [-2.7976e-01, -2.8719e-02,  2.8292e-01,  4.1799e-02,  2.8570e-04],
         [ 4.2156e-02, -2.9544e-01,  3.6284e-01,  3.5578e-01,  1.2462e-01],
         [ 3.2279e-01, -3.6989e-01,  2.4944e-01, -1.2068e-01,  1.9016e-01],
         [-3.7973e-02, -3.1601e-01, -1.2153e-01, -4.4226e-01, -2.3349e-01],
         [ 3.4167e-01, -1.0767e-01, -2.7544e-01,  2.1396e-01,  2.2648e-01],
         [ 5.5263e-02, -3.7972e-02, -2.7386e-01,  2.4645e-01, -2.9669e-01],
      

In [ ]:
# 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(num)

108


## weight initialization

In [ ]:
# 내 필기용 : He initialization 이 공식 문서랑 다르다? => paper에 맞게 구현됐고 torch 공식 문서만 틀림
import torch
from torch import nn

Fin=5000
Fout=1000
w = torch.zeros(141, Fin)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu') # forward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fin)))
w = torch.zeros(Fout, 212)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu') # backward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fout)))

# CNN?
N=32
C=64
H=6
W=10
w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(C*H*W))))

w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(N*H*W))))